Repository PlanBGmbH/flinkey-web-components, pull requests merged in 2022-01, with the labels that each got.

#47 Detect if all commits of PR come from dependabot and therefore skip version validation
  .github/workflows/Pull_Request.yml
Labels: needs-review

#53 ⬆️ Upgraded pipeline and NPM dependencies and fixed vulnerabilities
  .github/workflows/Build_Publish.yml
  .github/workflows/Pull_Request.yml
  components/CHANGELOG.md
  components/package-lock.json
  components/package.json
  components/stencil.config.ts
Labels: dependencies

#57 Chore/54 add tailwind to existing stencil project
  components/.prettierrc.json
  components/CHANGELOG.md
  components/package-lock.json
  components/package.json
  components/stencil.config.ts
  components/tailwind.config.js
Labels: under-review

#60 Chore/59 fix tailwind integration with proper packages
  components/CHANGELOG.md
  components/package-lock.json
  components/package.json
  components/stencil.config.ts
  components/tailwind.config.js
Labels: requires-changes

#62 👷 Improved Build & Publish workflow to define current date in GitHub …
  .github/workflows/Build_Publish.yml
Labels: needs-review
